version: "3"

networks:
    docker:
        driver: bridge

services:
    db:
        container_name: ${CONTAINER_PREFIX}.db
        hostname: db
        env_file: .env
        build:
            context: ./docker/db
            dockerfile: ./Dockerfile
        networks:
            - docker
        environment:
            - "MARIADB_DATABASE=${DB_DATABASE}"
            - "MARIADB_USER=${DB_USERNAME}"
            - "MARIADB_PASSWORD=${DB_PASSWORD}"
            - "MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - ./docker/db/custom.cnf:/bitnami/mariadb/conf/my.cnf:ro

    nginx:
        container_name: ${CONTAINER_PREFIX}.nginx
        hostname: nginx
        env_file: .env
        build:
            context: ./docker/nginx
            dockerfile: ./Dockerfile
        networks:
            - docker
        ports:
            - "${NGINX_PORT}:80"
        working_dir: /var/www/docker
        volumes:
            - ./code:/var/www/
            - ./.env:/var/www/.env

    php:
        container_name: ${CONTAINER_PREFIX}.php
        hostname: php
        env_file: .env
        build:
            context: ./docker/php
            dockerfile: ./Dockerfile
        networks:
            - docker
        working_dir: /var/www
        volumes:
            - ./code:/var/www/
            - ./.env:/var/www/.env

volumes:
    db-docker:
